### ISSUE TITLE
Provide acknowledgement functionality for alarms

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#14]
For new alarms we mean alarms that have been recently activated i.e. their state migrates to SET.
Such alarms should be displayed to properly catch the operator attention for example blinking. Once the user acknowledge the alarm, it remain red but stop blinking. The ACK action of the operator must be stored in the LTDB with a mandatory comment.

To avoid the display to be too noisy, the blinking should stop even if the user did not ACK the alarm after a reasonable time interval (5 seconds?).

A not ACK alarm that migrates back to CLEAR must stop blinking immediately but remains highlighted until the operator ACK it.

Note that the operator is supposed to ACK each new alarm even if it return to a state of UNSET. And for both cases the action is stored together with a mandatory message

**Comment by acaproni** [comment]
Note that REQ-HAND-006 states:
_Alarm acknowledgement (and shelving) should be possible from lists, process displays and overview displays on all the workstations_

**Comment by sfehlandt** [comment]
We will not do this for now: "To avoid the display to be too noisy, the blinking should stop even if the user did not ACK the alarm after a reasonable time interval (5 seconds?)."

We will discuss with end user what is the best way to proceed in such cases

**Comment by jmaldonadof** [comment]
The functionality to acknowledge alarms even if they change to CLEARED if the operator has not acknowledged yet was moved to the issue #30 and will be discussed separately

**Comment by jmaldonadof** [comment]
Closed in 8e5f8f815a3732a5c7e6d849b0a115a4a7451311
