### ISSUE TITLE
The system shall present a tabular view with all components that are in abnormal status

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#17]
We have this almost ready. but we should improve to display only alarms that do not depend on other alarms and only optionally all the alarms.
We have already the filtering that is IMO very important when dealing with many alarms.

From REQ-FUNC-006:
_This display shall contain all components, which are in abnormal status, e.g. in a tabular format. Each component shall provide all available information for the reason of the abnormal status (i.e. the reason that triggered an alarm). This display shall contain only the components, which triggered abnormal status and not the components that are in abnormal status as a result of summarizing the state of other components (i.e. if the HVAC system of antenna DA43 is in alarm, then the summarizing components “Array Element DA43” or “Antenna Array” should not be included in this list). It should, however, be possible to expand any shown element in both directions, i.e. the summary components it is contained in, as well as all the (sub-) components it contains_

**Comment by sfehlandt** [comment]
Closed by 9bbe8bc74dbf84628ca63640d8ce37b4ebba3dec

**Comment by sfehlandt** [comment]
Closed by 81cee0083c2da94f60a420c439b9a0e4c513b2da
