### ISSUE TITLE
Review the default order of the alarms in the table

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#21]
The alarms displayed in the table shall be ordered as follows
* active alarms first (valid ones on top)
* clear alarms after (valid ones on top)

Active alarms shall, in turn, be ordered by priority and lessicographically. 
Cleared alarms must, in turn,  be ordered lessicographically.

For example:
```
SET VALID PRI 2 *
SET VALID PRI 2 *
SET VALID PRI 1 *
SET INVALID PRI 4 #
SET INVALID PRI 2 #
CLEAR VALID @
CLEAR VALID  @
CLEAR INVALID %
CLEAR INVALID %
```

The groups, `*`, `#`, `@`, `%` must be ordered in alphabetical order.

**Comment by acaproni** [comment]
Had a meeting with Hector and he confirmed my proposal (we did not go into priorities):
* SET not ACK
* SET ACK
* SET invalid not ACK
* SET invalid ACK

**Comment by sfehlandt** [comment]
We are going to use this order:

| VAL     | VALIDITY | ACK     | PRIORITY |
|---------|----------|---------|----------|
| SET     | VALID    | NOT-ACK | CRITICAL |
| SET     | VALID    | NOT-ACK | HIGH     |
| SET     | VALID    | NOT-ACK | MEDIUM   |
| SET     | VALID    | NOT-ACK | LOW      |
| SET     | VALID    | ACK     | CRITICAL |
| SET     | VALID    | ACK     | HIGH     |
| SET     | VALID    | ACK     | MEDIUM   |
| SET     | VALID    | ACK     | LOW      |
| SET     | INVALID  | NOT-ACK | CRITICAL |
| SET     | INVALID  | NOT-ACK | HIGH     |
| SET     | INVALID  | NOT-ACK | MEDIUM   |
| SET     | INVALID  | NOT-ACK | LOW      |
| SET     | INVALID  | ACK     | CRITICAL |
| SET     | INVALID  | ACK     | HIGH     |
| SET     | INVALID  | ACK     | MEDIUM   |
| SET     | INVALID  | ACK     | LOW      |
| CLEARED | VALID    | NOT-ACK | ...      |
| CLEARED | VALID    | ACK     | ...      |
| CLEARED | INVALID  | NOT-ACK | ...      |
| CLEARED | INVALID  | ACK     | ...      |

In each category, alarms will be sorted alphabetically by Operational Mode
