### ISSUE TITLE
The table of alarm to show the description and provide link to documentation

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#24]
The table of alarms should have 
* a column with the description of the alarm as configured in the CDB
* a link to the documentation if provided in the CDB.

For the latter, Emilio and I agreed to have the link in the left most column i,.e. where there is the green/red icon.
It seems to me natural to have it in the short description as well.

For the records, we agreed to have the documentation in the ALMA wiki.

**Comment by mxolivares** [comment]
The required information, short description and url, is available in the current modal displayed after click on a row of the table (85bb73).

**Comment by mxolivares** [comment]
A short description column is available in the current table. Also, after click on every element of a row displays the modal with more information,  including the link to the ALMA Wiki. Because of terms of consistency, the option to associate the url with the alarm icon will be evaluated among other observations about the table components for the next releases. For now, the issue will be closed for the Release 3.

**Comment by mxolivares** [comment]
Closed with (eb3d6e7)

**Comment by mxolivares** [comment]
For the Release 3, the link will open a new tab going to https://www.alma.cl/. This is due to a pending confirmation about the url for the Alma Wiki.

**Comment by acaproni** [comment]
Maximiliano, this is not due to a pending confirmation. The documentation of each alarm is provided in the CDB configuration of IASIOs. The table should provided the link to that documentation page if available.

From our last meeting, my understanding is that the display is not yet able to fetch the URL from the documentation. To be implemented in the next release.

**Comment by mxolivares** [comment]
The component for the tabular view can display a link for more information from a service with mock data for the url from the CDB. Considering this, the issue will be closed for the Release 3. Still, the missing connection with the actual CDB will be followed on the Issues [ias-display#43](https://github.com/IntegratedAlarmSystem-Group/ias-display/issues/43) and [ias-webserver#32](https://github.com/IntegratedAlarmSystem-Group/ias-webserver/issues/32)
