### ISSUE TITLE
A not ACK alarm that changes back to CLEAR must stop blinking immediately but remains highlighted until the operator ACK it

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias-display#30]
A not ACK alarm that changes back to CLEAR must stop blinking immediately but remains highlighted until the operator ACK it.

Note that the operator is supposed to ACK each new alarm even if it return to a state of UNSET. And for both cases the action is stored together with a mandatory message

**Comment by sfehlandt** [comment]
Both Set and Cleared Alarms can (must) be acknowledged.
Alarms must be marked as unacknowledged until they are acknowledged.

**Comment by sfehlandt** [comment]
Closed by f2857e895733266489a0b1a707f9baece082bec4
