### ISSUE TITLE
Acknowledgment should not be available for cleared alarms

### ISSUE THREAD

**Issue by mxolivares** [IntegratedAlarmSystem-Group/ias-display#33]
Currently, a modal with the ACK option is displayed after click on every row of the alarms table. Components related to cleared alarms should not have the acknowledge option.

**Comment by acaproni** [comment]
Actually the ACK option must be displayed to all the alarms that have been set and never ACKed independently of their actual state. That means that that ACK option must be presented for an alarm that pass from SET to CLEAR before being ACK.

**Comment by sfehlandt** [comment]
Fixed along the development of the new version of the Table.
The comment about acknowledging Cleared Alarms that were never acknowledged will be addressed in the future.

Closed by: 6a6c9c7c28c3575726371c85854aee184e665567
