### ISSUE TITLE
Details for cleared alarms

### ISSUE THREAD

**Issue by mxolivares** [IntegratedAlarmSystem-Group/ias-display#34]
Required component to display the details for a selected alarm of the tabular view

**Comment by mxolivares** [comment]
Currently, a modal is displayed to ack alarms after make click on every row of the table. A details modal could be useful to display the required information.

**Comment by sfehlandt** [comment]
The details are in the table now.
Closed by c5bb864aff16202cd0145ce90f40154ce87fff64
