### ISSUE TITLE
Fix minor issues in styles after upgrade to Angular 6

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#47]
The issues are small, and are related to things that will probably be changed while working in  #41

**Comment by mxolivares** [comment]
- [ x] Remove borders on sidebar after build. Closed with (df494629)
- [ ]  Fix dimensions of the status view component after new development settings
- [ ]  Update tabular view style according to the material theme style

**Comment by mxolivares** [comment]
The display styles from the release 3 were recovered after (bfc64b1). Required changes under the use of angular material will be followed in #41.
