### ISSUE TITLE
Add preliminary color coding

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#5]
Alma memo 600 suggests a possible color coding for alarms in section 5.2.2:

Green: normal operational state
Yellow: validated warning state
Red: validates non nominal state
Blue: unknown/invalid state
Plum: alarm raised not validated
Grey: not configured or in maintenance

**Comment by acaproni** [comment]
Yes, this is a good starting point even if it does not cover all the possible cases. 
For example a shelved alarm with a different tone of green.

To support color blindness we shall probably mix different colors like Black on yellow for example

**Comment by sfehlandt** [comment]
UPDATE:
We need to consider patterns for the following combinations:

| Operational Mode  |     Clear     |      Set      |
| ----------------- | ------------- | ------------- |
| Invalid           |               |               |
| Startup           |               |               |
| Initialization    |               |               |
| Closing           |               |               |
| Shuttedown        |               |               |
| Operational       |               |               |
| Degraded          |               |               |
| Unknown           |               |               |
| Maintenance       |               |               |

**Comment by sfehlandt** [comment]
Preliminar proposal of color coding: https://integratedalarmsystem-group.github.io/ias_colors.html

**Comment by acaproni** [comment]
I think we are going in the right direction for the time being. The only point I have is that we are mapping too many operational state in the same color schema but the important is that the association can easily be modified in the future.

I  propose to have in green only operational and degraded and all the other mode mapped in another color i.e. have Purple (unknown), Maintenance (grey), Degraded+Operational (green), Startup+Initialization+Closing+ShuttedDown (?). This grouping seems to me more rationale than associating shutted down to operational.

**Comment by sfehlandt** [comment]
Actually we were considering addressing that with opacity. Take a look at the updated table: https://integratedalarmsystem-group.github.io/ias_colors.html

**Comment by acaproni** [comment]
Yes, it is a good idea.

Ale

**Comment by sfehlandt** [comment]
The proposal for Release 3 (yet to be tested with end-users is the following):

**Green:** Value = Cleared
**Red:** Value = Set (despite priority)
**Blue:** Operational mode = Unknown (despite Value Set or Cleared)
**Grey:** Operational mode = Maintenance or Shutteddown (despite Value Set or Cleared)

**Comment by sfehlandt** [comment]
Closed as for this proposal by 493761e3a6d1bcae34c0ed8148a52c91fda183b3
For future changes please open a new ticket

**Comment by mxolivares** [comment]
Note that the use of opacity was removed in the Release 3.
