### ISSUE TITLE
Stop Tabular View constant auto sorting

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#58]
Currenly, the tabular View maintains the default sorting all the time. This implies that when an Alarm changes its state its position in the table changes accordingly, which is confusing.

The sorting should be changed to be set when the user goes to the table, but when Alarms arrive, the table should not auto sort again. If the user wants to re-sort the table he/she can change the sorting manually by clicking in the desired column or re-navigating to the table from the navigation bar

**Comment by acaproni** [comment]
What if a new alarm arrives? I think in this case a resorting of the table is needed...

**Comment by sfehlandt** [comment]
The problem is that currently it is confusing because Alarms are being resorted too quickly.
Maybe we should discuss this in person in a scenario when things do move around a lot and decide then. So I am removing this issu from the milestone in order to decide later.

**Comment by sfehlandt** [comment]
We propose to show the alarms in the default sorting when the user opens the table only and stop the constan auto sorting.

When an alarm changes its status in a way that requires a resorting a notification will be shown to the user and the user will have the option to resort the whole table.

**Comment by sfehlandt** [comment]
We also propose to remove the validity as a criterio for sorting Alarms, as it cna effectively hide a problem of an Alarm changing from valid to invalid.
