### ISSUE TITLE
Update weather view to display nearby antennas instead of nearby pads and copy the real list of antennas

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#69]
Issues:
1. Currently the Weather display highlights all the pads associated to a weather station.
2. Also, the "Copy Antennas" button copies a hardcoded list of Strings.

Solutions:
1. The display should highlight only pads with antennas.
2. The button should copy the effective list of antennas associated

**Comment by mxolivares** [comment]
As an update for (2), the display will show pads according to a "free" or "in-use" status (with or without antennas), with highlighted pads will be related to the selected group.
