### ISSUE TITLE
Allow changing from the Shelve(Unshelve) confirmation view to the Unshelve(Shelve) if the user clicks the Shelve/Unshelve button

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#70]
Currently, when a user Shelves or Unshelves and Alarm a panel indicating that the process has been done is displayed.
If the user clicks the shelve/unshelve button of the same Alarm again (in order to perform the opposite action, e.g. Unshelve) nothing changes as the confirmation panel has not been closed.

This should be fixed, so the user does not have to close the panel in order to perform the opposite action. Note that this works is the user clicks the shelve/unshelve button of another Alarm, the problem is when it is the same alarm.

**Comment by mxolivares** [comment]
The issue was observed under new conditions for the actions. If required, related observations will be followed in new issues.
