### ISSUE TITLE
Reorder alarms in the antennas sidebar to add other components

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias-display#81]
The sidebar panel should include other array components (ex. correlator alarms, CLO alarm, etc) and all of them must be visible at the same time.

**Comment by jmaldonadof** [comment]
The size should be a height of 38px, with a line-height of 40px for a class related to the ‘grid-item’.

**Comment by mxolivares** [comment]
Closed with the reorganization of the alarms without the use of the antennas groups. The new organization implied that the conditions required for the styles of the alarms were no longer valid, except for the size of the alarms' badges. The size of the alarm badges will be considered as part of a general review for the graphical components according to the issue #75.

**Comment by mxolivares** [comment]
The size of the alarm badges will be considered as part of a general review for the graphical components according to the issue #75. The evaluation of colors should be part of a next review.
