### ISSUE TITLE
Add markers for the AOS and a compass Rose to the maps

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias-display#82]
Add a location for the AOS in the map and a compass Rose in order to locate the antennas from the OSF, because of questions from the AOS

**Comment by mxolivares** [comment]
The compass rose will not be included to prevent a misunderstanding of the coordinates used in the current map, which are not geographical coordinates. These coordinates were modified according to a previous work for ALMA, in order to have a better (and compact) display of the antennas.
